const properties = [
  {
    id: 1,
    image: "https://via.placeholder.com/150",
    price: "Php. 5,200,000",
    type: "HOUSE_LOT",
    category: "House and Lot",
    location: "M.V Hechanova Subd.",
    dateListed: "March 6, 2025",
    area: "100.00 sqm",
    bedrooms: 4,
    bathrooms: 4,
    status: "AVAILABLE",
    listingType: "DEVELOPER",
  },
  {
    id: 2,
    image: "https://via.placeholder.com/150",
    price: "Php. 3,800,000",
    type: "BUNGALOW",
    category: "House and Lot",
    location: "Quezon City",
    dateListed: "March 10, 2025",
    area: "80.00 sqm",
    bedrooms: 3,
    bathrooms: 2,
    status: "PENDING",
    listingType: "PRIVATE",
  },
  {
    id: 3,
    image: "https://via.placeholder.com/150",
    price: "Php. 2,500,000",
    type: "CONDO",
    category: "Condominium",
    location: "Makati",
    dateListed: "March 12, 2025",
    area: "50.00 sqm",
    bedrooms: 2,
    bathrooms: 1,
    status: "SOLD",
    listingType: "PRIVATE",
  },
];

export default properties;
